from pipelines.data_increment_effect import data_increment_effect_pipeline
from pipelines.download import download_pipeline
from pipelines.eda import eda_pipeline
from pipelines.low_cycle_prediction import low_cycle_prediction_pipeline
from pipelines.num_cycle_effect import num_cycle_effect_pipeline
from pipelines.sig_effect import sig_effect_pipeline
from pipelines.sparsity_robustness import sparsity_robustness_pipeline
from pipelines.training import training_pipeline
